import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

export class CampaignPage extends BasePage {
  createCampaignMenu: Locator;
  campaignIdField: Locator;
  campaignNameField: Locator;
  targetSizeField: Locator;
  createCampaignButton: Locator;
  successMessage: Locator;
  firstCampaignId: Locator;
  searchDropdown: Locator;
  searchInput: Locator;

  constructor(page: Page) {
    super(page);

    this.createCampaignMenu = page.locator('//span[contains(text(),"Create Campaign")]');
    this.campaignIdField = page.locator('[name="campaignId"]');
    this.campaignNameField = page.locator('[name="campaignName"]');
    this.targetSizeField = page.locator('[name="targetSize"]');
    this.createCampaignButton = page.getByRole('button', { name: 'Create Campaign' });
    this.successMessage = page.locator('//div[@role="alert"]');
    this.firstCampaignId = page.locator('//tr/td[1]').first();
    this.searchDropdown = page.locator('select.form-control');
    this.searchInput = page.locator('input[placeholder="Search by Campaign Id"]');
  }

  async openCreateCampaignForm() {
    await this.createCampaignMenu.click();
    await expect(this.campaignNameField).toBeVisible();
    await expect(this.targetSizeField).toBeVisible();
  }

  async verifyCampaignIdAutoGenerated() {
    await expect(this.campaignIdField).toHaveValue('Auto Generated');
  }

  async enterCampaignName(campaignName: string) {
    await this.campaignNameField.fill(campaignName);
  }

  async enterTargetSize(targetSize: string) {
    await this.targetSizeField.fill(targetSize);
  }

  async clickCreateCampaign() {
    await expect(this.createCampaignButton).toBeEnabled();
    await this.createCampaignButton.click();
  }

  async verifySuccessMessage() {
    await expect(this.successMessage).toContainText('Successfully Added');
  }

  async getCreatedCampaignId() {
    await expect(this.firstCampaignId).toBeVisible();
    return await this.firstCampaignId.innerText();
  }

  async createCampaign(campaignName: string, targetSize: string) {
    await this.openCreateCampaignForm();
    await this.verifyCampaignIdAutoGenerated();
    await this.enterCampaignName(campaignName);
    await this.enterTargetSize(targetSize);
    await this.clickCreateCampaign();
    await this.verifySuccessMessage();
  }

  async searchCampaignById(campaignId: string) {
    await expect(this.searchDropdown).toBeVisible();
    await this.searchDropdown.selectOption('campaignId');

    await expect(this.searchInput).toBeVisible();
    await this.searchInput.fill(campaignId);

    await expect(this.firstCampaignId).toContainText(campaignId);
  }

  async verifySearchedCampaignId(campaignId: string) {
    await expect(this.firstCampaignId).toContainText(campaignId);
  }
}





























/*import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

export class CampaignPage extends BasePage {
  createCampaignMenu: Locator;
  campaignIdField: Locator;
  campaignNameField: Locator;
  targetSizeField: Locator;
  createCampaignButton: Locator;
  successMessage: Locator;
  firstCampaignId: Locator;
  searchDropdown: Locator;
  searchInput: Locator;

  constructor(page: Page) {
    super(page);

    this.createCampaignMenu = page.locator('//span[contains(text(),"Create Campaign")]');
    this.campaignIdField = page.locator('[name="campaignId"]');
    this.campaignNameField = page.locator('[name="campaignName"]');
    this.targetSizeField = page.locator('[name="targetSize"]');
    this.createCampaignButton = page.getByRole('button', { name: 'Create Campaign' });
    this.successMessage = page.locator('//div[@role="alert"]');
    this.firstCampaignId = page.locator('//tr/td[1]').first();
    this.searchDropdown = page.locator('select.form-control');
    this.searchInput = page.locator('input[placeholder="Search by Campaign Id"]');
  }

  async openCreateCampaignForm() {
    await this.click(this.createCampaignMenu);
  }

  async verifyCampaignIdAutoGenerated() {
    await expect(this.campaignIdField).toHaveValue('Auto Generated');
  }

  async enterCampaignName(campaignName: string) {
    await this.type(this.campaignNameField, campaignName);
  }

  async enterTargetSize(targetSize: string) {
    await this.type(this.targetSizeField, targetSize);
  }

  async clickCreateCampaign() {
    await this.click(this.createCampaignButton);
  }

  async verifySuccessMessage() {
    await expect(this.successMessage).toContainText('Successfully Added');
  }

  async getCreatedCampaignId() {
    return await this.getText(this.firstCampaignId);
  }

  async createCampaign(campaignName: string, targetSize: string) {
    await this.openCreateCampaignForm();
    await this.verifyCampaignIdAutoGenerated();
    await this.enterCampaignName(campaignName);
    await this.enterTargetSize(targetSize);
    await this.clickCreateCampaign();
    await this.verifySuccessMessage();
  }

  // ✅ FIXED: smart wait instead of timeout
  async searchCampaignById(campaignId: string) {
    await this.searchDropdown.selectOption('campaignId');
    await this.searchInput.fill(campaignId);

    // wait until table updates with correct campaign
    await expect(this.firstCampaignId).toContainText(campaignId, { timeout: 10000 });
  }

  // ✅ clean verification (fast)
  async verifySearchedCampaignId(campaignId: string) {
    await expect(this.firstCampaignId).toContainText(campaignId);
  }
}*/
















/*import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

export class CampaignPage extends BasePage {
  createCampaignMenu: Locator;
  campaignIdField: Locator;
  campaignNameField: Locator;
  targetSizeField: Locator;
  createCampaignButton: Locator;
  successMessage: Locator;
  firstCampaignId: Locator;
  searchDropdown: Locator;
  searchInput: Locator;

  constructor(page: Page) {
    super(page);

    this.createCampaignMenu = page.locator('//span[contains(text(),"Create Campaign")]');
    this.campaignIdField = page.locator('[name="campaignId"]');
    this.campaignNameField = page.locator('[name="campaignName"]');
    this.targetSizeField = page.locator('[name="targetSize"]');
    this.createCampaignButton = page.getByRole('button', { name: 'Create Campaign' });
    this.successMessage = page.locator('//div[@role="alert"]');
    this.firstCampaignId = page.locator('//tr/td[1]').first();
     this.searchDropdown = page.locator('select.form-control');
    this.searchInput = page.locator('input[placeholder="Search by Campaign Id"]');
  }

  async openCreateCampaignForm() {
    await this.click(this.createCampaignMenu);
  }

  async verifyCampaignIdAutoGenerated() {
    await expect(this.campaignIdField).toHaveValue('Auto Generated');
  }

  async enterCampaignName(campaignName: string) {
    await this.type(this.campaignNameField, campaignName);
  }

  async enterTargetSize(targetSize: string) {
    await this.type(this.targetSizeField, targetSize);
  }

  async clickCreateCampaign() {
    await this.click(this.createCampaignButton);
  }

  async verifySuccessMessage() {
    await expect(this.successMessage).toContainText('Successfully Added');
  }

  async getCreatedCampaignId() {
    return await this.getText(this.firstCampaignId);
  }

  async createCampaign(campaignName: string, targetSize: string) {
    await this.openCreateCampaignForm();
   //await this.page.waitForTimeout(3000);
    await this.verifyCampaignIdAutoGenerated();
    //await expect(this.campaignIdField).toHaveAttribute('placeholder', 'Auto Generated');
    await this.enterCampaignName(campaignName);
    await this.enterTargetSize(targetSize);
    await this.clickCreateCampaign();
    await this.verifySuccessMessage();
    //await this.page.waitForTimeout(6000);
   
  }
  
 async searchCampaignById(campaignId: string) {
    await this.searchDropdown.selectOption('campaignId');
    await this.searchInput.fill(campaignId);
  }

  async verifySearchedCampaignId(campaignId: string) {
    await expect(this.firstCampaignId).toContainText(campaignId);
  }
}*/
