import { Page, Locator, expect } from '@playwright/test';

export class ContactPage {
  private page: Page;

  private contactsLink: Locator;
  private createContactMenu: Locator;
  private contactIdInput: Locator;
  private organizationInput: Locator;
  private titleInput: Locator;
  private contactNameInput: Locator;
  private mobileInput: Locator;
  private plusIcon: Locator;
  private createContactBtn: Locator;
  private successMsg: Locator;
  private firstTableCell: Locator;
  private searchDropdown: Locator;
  private searchInput: Locator;

  constructor(page: Page) {
    this.page = page;

    this.contactsLink = page.getByRole('link', { name: 'Contacts' });
    this.createContactMenu = page.locator('span:has-text("Create Contact")');
    this.contactIdInput = page.locator('[name="contactId"]');
    this.organizationInput = page.locator('[name="organizationName"]');
    this.titleInput = page.locator('[name="title"]');
    this.contactNameInput = page.locator('[name="contactName"]');
    this.mobileInput = page.locator('[name="mobile"]');
    this.plusIcon = page.locator('[data-icon="plus"]');
    this.createContactBtn = page.getByRole('button', { name: 'Create Contact' });
    this.successMsg = page.locator('//div[@role="alert"]');
    this.firstTableCell = page.locator('//tr/td[1]').first();
    this.searchDropdown = page.locator('select.form-control');
    this.searchInput = page.locator('input[placeholder="Search by Contact Id"]');
  }

  async openCreateContactForm() {
    await this.contactsLink.click();
    await this.createContactMenu.click();
  }

  async verifyContactIdAutoGenerated() {
    await expect(this.contactIdInput).toHaveValue('Auto Generated');
  }

  async fillOrganization(organization: string) {
    await this.organizationInput.fill(organization);
    await expect(this.organizationInput).toHaveValue(organization);
  }

  async fillTitle(title: string) {
    await this.titleInput.fill(title);
    await expect(this.titleInput).toHaveValue(title);
  }

  async fillContactName(name: string) {
    await this.contactNameInput.fill(name);
  }

  async fillMobile(phone: string) {
    await this.mobileInput.fill(phone);
    await expect(this.mobileInput).toHaveValue(phone);
  }

  async selectCampaignFromPopup() {
    const popupPromise = this.page.waitForEvent('popup');
    await this.plusIcon.click();

    const popup = await popupPromise;
    await popup.waitForLoadState();
    await popup.getByRole('button', { name: 'Select' }).first().click();
  }

  async clickCreateContact() {
    await this.createContactBtn.click();
  }

  async verifySuccessMessage() {
    await expect(this.successMsg).toBeVisible();
    await expect(this.successMsg).toContainText('Successfully Added');
  }

  async getCreatedContactId(): Promise<string> {
    const contactId = await this.firstTableCell.innerText();
    return contactId.trim();
  }

  async searchContactById(contactId: string) {
    await this.searchDropdown.selectOption('contactId');
    await this.searchInput.fill(contactId);
  }

  async verifySearchedContactId(contactId: string) {
    await expect(this.firstTableCell).toContainText(contactId);
  }

  async createContact(data: {
    organization: string;
    title: string;
    contactName: string;
    mobile: string;
  }): Promise<string> {
    await this.openCreateContactForm();
    await this.verifyContactIdAutoGenerated();
    await this.fillOrganization(data.organization);
    await this.fillTitle(data.title);
    await this.fillContactName(data.contactName);
    await this.fillMobile(data.mobile);
    await this.selectCampaignFromPopup();
    await this.clickCreateContact();
    await this.verifySuccessMessage();

    return await this.getCreatedContactId();
  }
}